export const SKILL_CATEGORIES = [
  {
    id: 'digital-design',
    label: 'Digital & Design',
    description: 'UI, visual polish, editing and online creative help.',
    sampleSkills: [
      'Landing page UI review',
      'Canva poster design',
      'Instagram reel editing',
      'Figma mobile app polish',
    ],
  },
  {
    id: 'tech-coding',
    label: 'Tech & Coding',
    description: 'Coding help, setup support and practical digital tools.',
    sampleSkills: [
      'React basics mentoring',
      'Python beginner support',
      'Laptop setup and software install',
      'Excel dashboard help',
    ],
  },
  {
    id: 'language-career',
    label: 'Language & Career',
    description: 'Communication, interviews and job-readiness skills.',
    sampleSkills: [
      'Spoken English practice',
      'Resume improvement',
      'Interview speaking drills',
      'Presentation confidence coaching',
    ],
  },
  {
    id: 'fitness-wellness',
    label: 'Fitness & Wellness',
    description: 'Body movement, energy and everyday wellness support.',
    sampleSkills: [
      'Morning yoga flow',
      'Home workout coaching',
      'Meditation guidance',
      'Mobility reset sessions',
    ],
  },
  {
    id: 'music-arts',
    label: 'Music & Arts',
    description: 'Creative hobbies and skill-sharing sessions.',
    sampleSkills: [
      'Guitar basics class',
      'Singing practice coaching',
      'Sketching fundamentals',
      'Dance choreography basics',
    ],
  },
  {
    id: 'home-daily-life',
    label: 'Home & Daily Life',
    description: 'Useful everyday local skills people can hire nearby.',
    sampleSkills: [
      'Home cooking lessons',
      'Mehndi design service',
      'Photography basics walk',
      'Tailoring and basic stitching help',
    ],
  },
];

export const SUGGESTED_SKILL_NAMES = SKILL_CATEGORIES.flatMap((category) => category.sampleSkills);

export const SAMPLE_SKILLS = [
  {
    id: 'skill-101',
    title: 'Landing Page UI Review',
    category: 'Digital & Design',
    instructorName: 'Aanya Singh',
    rating: 4.9,
    price: 1200,
    mode: 'Hybrid',
    level: 'Intermediate',
    distanceKm: 2.4,
    area: 'Raj Nagar Extension',
    responseTime: 'Replies in 8 min',
    experience: '4 years experience',
    availability: 'Today, 6:30 PM',
    learnersHelped: 48,
    accent: 'linear-gradient(135deg, #0f172a 0%, #2563eb 100%)',
    description:
      'Best for founders and students who want cleaner hierarchy, sharper mobile UI and fast visual polish.',
    tags: ['Figma', 'Mobile UI', 'Landing page'],
    outcomes: [
      'Improve layout hierarchy and spacing.',
      'Polish hero section and mobile responsiveness.',
      'Get quick feedback for the next design iteration.',
    ],
  },
  {
    id: 'skill-102',
    title: 'Interview Speaking Drills',
    category: 'Language & Career',
    instructorName: 'Kabir Khan',
    rating: 4.8,
    price: 900,
    mode: 'Local meetup',
    level: 'Beginner friendly',
    distanceKm: 6.8,
    area: 'Indirapuram',
    responseTime: 'Usually replies in 15 min',
    experience: '5 years coaching',
    availability: 'Tomorrow, 8:00 AM',
    learnersHelped: 62,
    accent: 'linear-gradient(135deg, #7c2d12 0%, #f59e0b 100%)',
    description:
      'Focused speaking practice for confidence, fluency and practical interview answers in real situations.',
    tags: ['English', 'Interviews', 'Confidence'],
    outcomes: [
      'Practice answers for common interview questions.',
      'Reduce hesitation and improve fluency.',
      'Get drills you can repeat at home.',
    ],
  },
  {
    id: 'skill-103',
    title: 'Morning Yoga Flow',
    category: 'Fitness & Wellness',
    instructorName: 'Meera Joshi',
    rating: 4.9,
    price: 700,
    mode: 'Park session',
    level: 'All levels',
    distanceKm: 1.6,
    area: 'Vaishali Sector 3',
    responseTime: 'Replies in 5 min',
    experience: '6 years training',
    availability: 'Sunday, 7:00 AM',
    learnersHelped: 84,
    accent: 'linear-gradient(135deg, #065f46 0%, #22c55e 100%)',
    description:
      'Short, energizing yoga and mobility sessions for working people who want better posture and less stiffness.',
    tags: ['Yoga', 'Mobility', 'Morning routine'],
    outcomes: [
      'Improve flexibility and body movement.',
      'Learn a repeatable home warm-up.',
      'Reduce desk-job stiffness and fatigue.',
    ],
  },
  {
    id: 'skill-104',
    title: 'Instagram Reel Editing',
    category: 'Digital & Design',
    instructorName: 'Dev Malhotra',
    rating: 4.7,
    price: 1500,
    mode: 'Online',
    level: 'Intermediate',
    distanceKm: 12.4,
    area: 'Noida Sector 62',
    responseTime: 'Replies in 20 min',
    experience: '3 years editing',
    availability: 'Friday, 9:30 PM',
    learnersHelped: 37,
    accent: 'linear-gradient(135deg, #312e81 0%, #2563eb 100%)',
    description:
      'Reel polish for pacing, transitions, captions and final export quality for social media creators.',
    tags: ['Reels', 'Editing', 'Content'],
    outcomes: [
      'Tighten cut rhythm and transitions.',
      'Improve caption and sound balance.',
      'Export sharper social-ready videos.',
    ],
  },
  {
    id: 'skill-105',
    title: 'Canva Poster Design',
    category: 'Digital & Design',
    instructorName: 'Riya Arora',
    rating: 4.6,
    price: 650,
    mode: 'Home visit',
    level: 'Beginner friendly',
    distanceKm: 4.2,
    area: 'Crossings Republik',
    responseTime: 'Replies in 12 min',
    experience: '2 years freelance',
    availability: 'Today, 5:00 PM',
    learnersHelped: 29,
    accent: 'linear-gradient(135deg, #7c3aed 0%, #ec4899 100%)',
    description:
      'Great for students, small shops and creators who need quick, clean posters and social creatives.',
    tags: ['Canva', 'Poster', 'Social media'],
    outcomes: [
      'Create clean posters faster.',
      'Learn text hierarchy and color balance.',
      'Build templates you can reuse later.',
    ],
  },
  {
    id: 'skill-106',
    title: 'Guitar Basics Class',
    category: 'Music & Arts',
    instructorName: 'Arnav Bansal',
    rating: 4.8,
    price: 800,
    mode: 'Local meetup',
    level: 'Beginner',
    distanceKm: 3.5,
    area: 'Vasundhara',
    responseTime: 'Replies in 10 min',
    experience: '5 years performing',
    availability: 'Saturday, 4:00 PM',
    learnersHelped: 41,
    accent: 'linear-gradient(135deg, #7c2d12 0%, #f97316 100%)',
    description:
      'Friendly beginner sessions for chords, rhythm and song practice without making things feel complicated.',
    tags: ['Guitar', 'Music', 'Beginner'],
    outcomes: [
      'Learn basic chords and rhythm.',
      'Play a simple song progression.',
      'Build a short home practice routine.',
    ],
  },
  {
    id: 'skill-107',
    title: 'Excel Dashboard Help',
    category: 'Tech & Coding',
    instructorName: 'Neha Verma',
    rating: 4.8,
    price: 1100,
    mode: 'Hybrid',
    level: 'Intermediate',
    distanceKm: 5.1,
    area: 'Shipra Suncity',
    responseTime: 'Replies in 9 min',
    experience: '7 years analytics',
    availability: 'Tomorrow, 11:30 AM',
    learnersHelped: 56,
    accent: 'linear-gradient(135deg, #065f46 0%, #0f766e 100%)',
    description:
      'Practical help for reports, dashboards and Excel cleanup when you want faster working sheets.',
    tags: ['Excel', 'Dashboard', 'Office work'],
    outcomes: [
      'Organize data into a clean dashboard.',
      'Improve formulas and sheet structure.',
      'Make reporting easier to understand.',
    ],
  },
  {
    id: 'skill-108',
    title: 'Home Cooking Lessons',
    category: 'Home & Daily Life',
    instructorName: 'Sonal Gupta',
    rating: 4.9,
    price: 950,
    mode: 'Home visit',
    level: 'All levels',
    distanceKm: 2.9,
    area: 'Kaushambi',
    responseTime: 'Replies in 7 min',
    experience: '8 years teaching',
    availability: 'Sunday, 1:00 PM',
    learnersHelped: 33,
    accent: 'linear-gradient(135deg, #92400e 0%, #f59e0b 100%)',
    description:
      'Simple practical cooking sessions for daily meals, beginner kitchen confidence and clean preparation habits.',
    tags: ['Cooking', 'Home skill', 'Beginner'],
    outcomes: [
      'Learn repeatable everyday recipes.',
      'Improve cutting, prep and timing.',
      'Cook confidently without relying on videos every time.',
    ],
  },
];
